[user]
# Update to use conditional variables when this is released:
# https://github.com/jj-vcs/jj/commit/f5d450d7c3a8f8a49e30aef0fd18d8295ffc8cb6
name = "Robert Jackson"
email = "me@rwjblue.com"

[ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"

[ui.diff]
# NOTE: this is required when using `delta` as a pager
format = "git"

[git]
# https://jj-vcs.github.io/jj/latest/config/#set-of-private-commits
private-commits = 'description(glob:"private:*")'
# https://jj-vcs.github.io/jj/latest/config/#prefix-for-generated-bookmarks-on-push
push-bookmark-prefix = "rwjblue/push-"

[templates]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#default-description
draft_commit_description = '''
  concat(
    description,
    "\n",
    "JJ: This commit contains the following changes:\n",
    indent("JJ:    ", diff.stat(72)),
    "\n",
    "JJ: ignore-rest\n",
    diff.git(),
  )
'''
