# ~/.config/sheldon/plugins.toml

[plugins.prezto-completion]
github = "sorin-ionescu/prezto"
use = ["modules/completion/init.zsh"]
apply = ["source"]

[plugins.local-completions]
local = "~/.zsh/completions"
use = ["*"]
apply = ["fpath"]

[plugins.local-plugins]
local = "~/.zsh/plugins"
use = ["*"]
apply = ["source"]
