"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
# Update to use conditional variables when this is released:
# https://github.com/jj-vcs/jj/commit/f5d450d7c3a8f8a49e30aef0fd18d8295ffc8cb6
name = "Robert Jackson"
email = "me@rwjblue.com"


[core]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#watchman
fsmonitor = "watchman"
watchman.register_snapshot_trigger = true

[git]
# https://jj-vcs.github.io/jj/latest/config/#set-of-private-commits
private-commits = 'description(glob:"private:*")'
# https://jj-vcs.github.io/jj/latest/config/#prefix-for-generated-bookmarks-on-push
push-bookmark-prefix = "rwjblue/push-"
# This will become the default in a future version (it also fixes issues with using git@github.com remotes)
# per https://github.com/jj-vcs/jj/releases/tag/v0.26.0
subprocess = true
sign-on-push = true

# See https://github.com/jj-vcs/jj/discussions/3750
[signing]
behavior = "drop"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG90UNRupC9GKqqXL8/5TZ3mQAE6lzN4517Isklyxk8a"

[signing.backends.ssh]
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[[--scope]]
--when.repositories = ["~/src/github/linkedin/"]

[--scope.user]
email = "rjackson@linkedin.com"

[[--scope]]
--when.repositories = [
  "~/src/github/gleanwork/",
  "~/src/github/askscio/",
  "~/src/github/rwjblue/dotfiles/local-packages/",
]

[--scope.user]
email = "robert.jackson@glean.com"

[--scope.signing]
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINnJAefwOOhSTp/bxJjFJXVluHPG7hMjgLCVqBZ/YlAW"

# Configuration for repositories where I push directly to trunk() (e.g. personal dotfiles)
[[--scope]]
--when.repositories = ["~/src/github/rwjblue/"]

[--scope.aliases]
update-trunk = ["bookmark", "move", "--from", "trunk()", "--to", "@-"]

[[--scope]]
--when.commands = ["diff"]

[--scope.ui]
# NOTE: When using `delta` as the pager globally (e.g. for commands other than
# `jj diff`) forces the terminal output to be cleared when the pager is closed
# (because delta doesn't invoke `less` with `-X` option). This changes to only
# use `delta` for `jj diff`.
# See:
#  - https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
#  - https://github.com/jj-vcs/jj/issues/4142
#  - https://github.com/jj-vcs/jj/discussions/4690
pager = "delta"
diff.format = "git"

[revset-aliases]

# View the entire branch being worked on
'slice()' = 'slice(@)'
'slice(from)' = 'ancestors(reachable(from, mutable()), 2)'

# All my commits that haven't landed yet. This is the workhorse.
'open()' = 'open(mine())'
'open(domain)' = 'domain ~ ::immutable_heads()'

# All open remote branches
'ropen()' = 'ancestors(::remote_bookmarks() ~ immutable(), 2)'

# history leading up to the working copy, like git log
'last()' = 'last(20)'
'last(n)' = 'ancestors(@, n)'

# view a revision's ancestry back to where it diverged from trunk()
'stack()' = 'stack(@)'
'stack(from)' = 'ancestors((immutable()..from) | from::, 2)'

'private()' = 'description(glob:"private:*")'

# find all the bookmarks on my current set of revisions, excluding trunk()
'local_bookmarks()' = 'heads(::@- & (bookmarks() ~ trunk()))'

[aliases]

# abbreviations
b = ["bookmark"]
sq = ["squash"]
ws = ["workspace"]

# viewing history
open = ["log", "-r", "open(mine())"]
ropen = ["log", "-r", "ropen()"]
recent = ["log", "-r", "last()"]

# bring a branch up to date with trunk()
# works with `jj update` alone or with `-b REV`
up = ["rebase", "--skip-emptied", "-d", "trunk()"]

# move any local bookmarks forward to the latest commit on trunk()
update-bookmark = [
  'bookmark',
  'move',
  '--from',
  'local_bookmarks()',
  '--to',
  '@-',
]

# rebase any private commits onto trunk()
rebase-private = ["rebase", "--skip-emptied", "-r", "private()", "-d", "@"]

[templates]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#default-description
draft_commit_description = '''
  concat(
    description,
    "\n",
    "JJ: This commit contains the following changes:\n",
    indent("JJ:    ", diff.summary()),
    "\n",
    "JJ: ignore-rest\n",
    diff.git(),
  )
'''
