"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
# Update to use conditional variables when this is released:
# https://github.com/jj-vcs/jj/commit/f5d450d7c3a8f8a49e30aef0fd18d8295ffc8cb6
name = "Robert Jackson"
email = "me@rwjblue.com"

[[--scope]]
--when.repositories = ["~/src/linkedin/"]

[--scope.user]
email = "rjackson@linkedin.com"

# Configuration for repositories where I push directly to trunk() (e.g. personal dotfiles)
[[--scope]]
--when.repositories = ["~/src/rwjblue/"]

[--scope.aliases]
update-trunk = ["bookmark", "move", "--from", "trunk()", "--to", "@-"]


[core]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#watchman
fsmonitor = "watchman"
watchman.register_snapshot_trigger = true

[ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"

[ui.diff]
# NOTE: this is required when using `delta` as a pager
format = "git"

[git]
# https://jj-vcs.github.io/jj/latest/config/#set-of-private-commits
private-commits = 'description(glob:"private:*")'
# https://jj-vcs.github.io/jj/latest/config/#prefix-for-generated-bookmarks-on-push
push-bookmark-prefix = "rwjblue/push-"
# This will become the default in a future version (it also fixes issues with using git@github.com remotes)
# per https://github.com/jj-vcs/jj/releases/tag/v0.26.0
subprocess = true

[revset-aliases]

# View the entire branch being worked on
'slice()' = 'slice(@)'
'slice(from)' = 'ancestors(reachable(from, mutable()), 2)'

# All my commits that haven't landed yet. This is the workhorse.
'open()' = 'open(mine())'
'open(domain)' = 'domain ~ ::immutable_heads()'

# All open remote branches
'ropen()' = 'ancestors(::remote_bookmarks() ~ immutable(), 2)'

# history leading up to the working copy, like git log
'last()' = 'last(20)'
'last(n)' = 'ancestors(@, n)'

# view a revision's ancestry back to where it diverged from trunk()
'stack()' = 'stack(@)'
'stack(from)' = 'ancestors((immutable()..from) | from::, 2)'

'private()' = 'description(glob:"private:*")'

[aliases]

# abbreviations
b = ["bookmark"]
sq = ["squash"]
ws = ["workspace"]

# viewing history
open = ["log", "-r", "open(mine())"]
ropen = ["log", "-r", "ropen()"]

# bring a branch up to date with trunk()
# works with `jj update` alone or with `-b REV`
up = ["rebase", "--skip-emptied", "-d", "trunk()"]

# rebase any private commits onto trunk()
rebase-private = ["rebase", "--skip-emptied", "-r", "private()", "-d", "@"]

[templates]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#default-description
draft_commit_description = '''
  concat(
    description,
    "\n",
    "JJ: This commit contains the following changes:\n",
    indent("JJ:    ", diff.summary()),
    "\n",
    "JJ: ignore-rest\n",
    diff.git(),
  )
'''
