#:schema ../crates/config/config_schema.json

[[tmux.sessions]]
name = "✅ todos"

[[tmux.sessions.windows]]
name = "todos"

[[tmux.sessions]]
name = "dotfiles"

[[tmux.sessions.windows]]
name = "dotvim"
path = "~/src/rwjblue/dotvim"
command = "nvim"

[[tmux.sessions.windows]]
name = "dotfiles"
path = "~/src/rwjblue/dotfiles"
command = "nvim"
