#!/bin/bash

if [[ ! -f ~/.local/bin/task ]]; then
  # Install task
  mkdir -p ~/.local/bin
  sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
fi

export PATH="$PATH:$HOME/.local/bin"

task install
