# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[[battery.display]]
# "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]
# "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# when capacity is over 30%, the battery indicator will not be displayed

[shell]
# While I'm working to learn `fish` and swap as my default shell it's really nice to know
# which shell I'm currently using. This is a nice way to do that.
fish_indicator = '🐟 '
zsh_indicator = '🚀 '
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[custom.jj]
# combining `jj root` here to avoid having to execute `jj` multiple times
# this brings the total timings for `custom.jj` from 63ms down to 25ms
command = '''
jj root --ignore-working-copy > /dev/null 2>&1 && jj log --no-graph --color always --revisions @ --template '
  surround(
    "(",
    ")",
    separate(
      " ",
      change_id.shortest(8),
      commit_id.shortest(8),
      if(empty, label("empty", "(empty)")),
      if(description,
        concat("\"", description.first_line(), "\""),
        label(if(empty, "empty"), description_placeholder),
      ),
      bookmarks.join(", "),
      branches.join(", "),
      if(conflict, "💥"),
      if(divergent, "🚧"),
      if(hidden, "👻"),
      if(immutable, "🔒"),
    )
  )
'
'''
when = true
symbol = "🍐"
