# ~/.config/sheldon/plugins.toml
shell = "zsh"

[plugins.prezto-completion]
github = "sorin-ionescu/prezto"
use = ["modules/completion/init.zsh"]
apply = ["source"]

[plugins.homebrew-completions]
local = "/opt/homebrew/share/zsh/site-functions/"
use = ["*"]
apply = ["fpath"]

[plugins.local-completions]
local = "~/.zsh/completions"
use = ["*"]
apply = ["fpath"]

[plugins.local-plugins]
local = "~/.zsh/plugins"
use = ["*"]
apply = ["source"]

[plugins.compinit]
inline = 'autoload -Uz compinit'
