# ~/.config/sheldon/plugins.toml

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-async]
github = "mafredri/zsh-async"
use = ["async.zsh"]
apply = ["defer"]

[plugins.prezto-history]
github = "sorin-ionescu/prezto"
use = ["modules/history/init.zsh"]
# for history to work, it must be sourced eagerly
apply = ["source"]

[plugins.prezto-completion]
github = "sorin-ionescu/prezto"
use = ["modules/completion/init.zsh"]
apply = ["defer"]

[plugins.local-completions]
local = "~/.zsh/completions"
use = ["*"]
apply = ["fpath"]

[plugins.local-plugins]
local = "~/.zsh/plugins"
use = ["*"]
apply = ["defer"]
