[package]
name = "binutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
cargo_metadata = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
regex = { workspace = true }
shellexpand = { workspace = true }
latest_bin = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
temp-env = { workspace = true }
rand = { workspace = true }
test_utils = { workspace = true }
fixturify = { workspace = true }
