[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
schemars = "0.8.21"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
tracing = "0.1.40"

[dev-dependencies]
insta = { version = "1.36.1", features = ["yaml", "toml"] }
tempfile = "3.10.1"
test_utils = { path = "../test_utils" }

[build-dependencies]
anyhow = "1.0.79"
schemars = "0.8.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.122"
