# CMD: sheldon source
# OUTPUT START: sheldon source
source "/Users/rjackson/.local/share/sheldon/repos/github.com/romkatv/zsh-defer/zsh-defer.plugin.zsh"
zsh-defer source "/Users/rjackson/.local/share/sheldon/repos/github.com/sorin-ionescu/prezto/modules/completion/init.zsh"
fpath=( "/opt/homebrew/share/zsh/site-functions/" $fpath )
fpath=( "/Users/rjackson/.zsh/completions" $fpath )
source "/Users/rjackson/.zsh/plugins/1password.zsh"
source "/Users/rjackson/.zsh/plugins/atuin.zsh"
source "/Users/rjackson/.zsh/plugins/basic_config.zsh"
source "/Users/rjackson/.zsh/plugins/bat.zsh"
source "/Users/rjackson/.zsh/plugins/brew.zsh"
source "/Users/rjackson/.zsh/plugins/cargo.zsh"
source "/Users/rjackson/.zsh/plugins/fzf.zsh"
source "/Users/rjackson/.zsh/plugins/git.zsh"
source "/Users/rjackson/.zsh/plugins/pyenv.zsh"
source "/Users/rjackson/.zsh/plugins/rbenv.zsh"
source "/Users/rjackson/.zsh/plugins/ssh.zsh"
source "/Users/rjackson/.zsh/plugins/starship.zsh"
source "/Users/rjackson/.zsh/plugins/tmux.zsh"
source "/Users/rjackson/.zsh/plugins/unixy_utilities.zsh"
source "/Users/rjackson/.zsh/plugins/volta.zsh"
source "/Users/rjackson/.zsh/plugins/zoxide.zsh"
zsh-defer source "/Users/rjackson/.zsh/plugins_deferred/.gitkeep"
autoload -Uz compinit && zsh-defer compinit

# OUTPUT END: sheldon source
