# Most of the local configuration is done via the individual files in zsh/plugins/*
eval "$(sheldon source)"

# load local (non-suitable for pushing to GH) tweaks
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
