[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.3", features = ["derive"] }
latest_bin = { git = "https://github.com/malleatus/shared_binutils.git" }
schemars = "0.8.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.122"
serde_yml = "0.0.11"
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
insta = { version = "1.36.1", features = ["yaml", "toml"] }
tempfile = "3.10.1"
test_utils = { path = "../test_utils" }
